### ISSUE TITLE
Bug corrigindo m003.c

### ISSUE THREAD

**Issue by gab-urbano** [courselab/prog2020-gab-urbano#2]
O programa corretamente responde 1 para números primos mas o autograding denuncia como erro. Não sei ler o input do autograding.

**Comment by monacofj** [comment]
Opps... 
You're a good programmer. It seems the bug is in your math ;-)

https://en.wikipedia.org/wiki/Prime_number

By definition, the first prime is 2.

**Comment by gab-urbano** [comment]
Mathmaticians why do you do this to me! It'll be fixed right now
